query InstalledThermistorChainPointPaginated($first: Int!, $page: Int){
    InstalledThermistorChainPointPaginated(first: $first, page: $page){
        paginatorInfo{
            count
            currentPage
            firstItem
            hasMorePages
            lastItem
            lastPage
            perPage
            total
        }
        data{
            installed_thermistor_chains_id
            id
            deep
            created_at
            updated_at
            min_warning_temperature
            max_warning_temperature
            min_critical_temperature
            max_critical_temperature
            installed_thermistor_chain
        }
    }
}