query MeteringThermistorChainPoint($id: ID!){
    MeteringThermistorChainPoint(id: $id){
        id
        metering_thermistor_chain_id
        created_at
        updated_at
        value
        unit_id
        metering_thermistor_chain
    }
}